### ISSUE TITLE
provide default implementation of __repr__

### ISSUE THREAD

**Issue by wtjones** [quiqueporta/simple-value-object#1]
I added some logging to my app and started seeing this when `pprint`ing properties that are of type `ValueObject`:

```
<domain.model.term.Term object at 0x1134653c8>
```

Since my current value objects have only one property, I simply do this:

```
def __str__(self):
        return self.name
def __repr__(self):
        return self.name
```
It could be handy to have a default (and __str__?) that does a pprint on all the known properties.

**Comment by quiqueporta** [comment]
The object representation could be different for each user.
What's your proposal for default representation?

**Comment by wtjones** [comment]
Since value objects are generally a flat set of primitives (testing this resulted in #4), one way would be to do something like this, but iterate the properties: 

from [dbader.org](https://dbader.org/blog/python-repr-vs-str)
```
 def __repr__(self):
       return (f'{self.__class__.__name__}('
               f'{self.color!r}, {self.mileage!r})')
```

**Comment by javierfdezg** [comment]
There is another implementation of value object around that has an implementation for __repr__: 

https://github.com/keleshev/value/blob/master/value.py#L23

Maybe is a good source to get ideas from.

**Comment by quiqueporta** [comment]
Ok, I will check it

**Comment by quiqueporta** [comment]
A new version with objects representation is available :wink: 
Thanks to all
